apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordinvite-banano-cc
  namespace: banano-discordinvite
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: discordinvite-banano-cc
  template:
    metadata:
      labels:
        app: discordinvite-banano-cc
    spec:
      containers:
        - name: discordinvite-banano-cc
          image: bananocoin/discordinvite:1
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 8008
              name: api
          command: ["/bin/bash", "-c"]
          args: ["python server.py --host 0.0.0.0"]
          env:
            - name: RECAPTCHA_SECRET
              valueFrom:
                secretKeyRef:
                  name: discordinvite-banano-cc
                  key: recaptcha_secret
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discordinvite-banano-cc
                  key: discord_token
            - name: DISCORD_CHANNEL_ID
              value: "416344480820494356"
