apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: discordapi-banano
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - discordinvite.banano.cc
    secretName: discordinvite-banano-cc-server-secret
  rules:
  - host: discordinvite.banano.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: chat-banano-cc
          servicePort: 8008