apiVersion: v1
kind: Service
metadata:
  name: discordinvite-banano-cc
  namespace: banano-discordinvite
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: 8008
      name: api
  selector:
    app: discordinvite-banano-cc
